# Usa un'immagine di base di Linux
FROM gcc:latest


# Imposta la directory di lavoro nel container
WORKDIR /app

# Copia i file sorgente nel container
COPY cliente.c autopilota.sh /app/

# Compila il programma e specifica il nome dell'eseguibile di output
RUN gcc -o cliente cliente.c

# Rendi il file autopilota.sh eseguibile
RUN chmod 777 autopilota.sh

# Avvia 10 clienti
CMD ["./cliente", "autopilota"]
